/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.menu2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabiorestrepo
 */
public class sales1 extends javax.swing.JFrame {

    /**
     * Creates new form sales1
     */
    public sales1() {
        initComponents();
        
       
    }
     DefaultTableModel model;
     int qty;
     double price;
     double sum = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        view = new javax.swing.JPanel();
        liquor = new javax.swing.JPanel();
        scotchB = new javax.swing.JButton();
        ginB = new javax.swing.JButton();
        vodkaB = new javax.swing.JButton();
        beverage = new javax.swing.JPanel();
        cokeB = new javax.swing.JButton();
        gingerB = new javax.swing.JButton();
        spriteB = new javax.swing.JButton();
        food = new javax.swing.JPanel();
        burgerB = new javax.swing.JButton();
        pizzaB = new javax.swing.JButton();
        croutonsB = new javax.swing.JButton();
        categories = new javax.swing.JPanel();
        beveragesB = new javax.swing.JButton();
        liquorB = new javax.swing.JButton();
        foodB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totallabel = new javax.swing.JLabel();
        qtylabel = new javax.swing.JTextField();
        sendB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        header.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("MENU");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unit", "Item", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        view.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));
        view.setLayout(new java.awt.CardLayout());

        liquor.setBackground(new java.awt.Color(0, 255, 0));

        scotchB.setText("Scotch");
        scotchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scotchBActionPerformed(evt);
            }
        });

        ginB.setText("Gin");
        ginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ginBActionPerformed(evt);
            }
        });

        vodkaB.setText("Vodka");
        vodkaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vodkaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout liquorLayout = new javax.swing.GroupLayout(liquor);
        liquor.setLayout(liquorLayout);
        liquorLayout.setHorizontalGroup(
            liquorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liquorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(vodkaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scotchB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ginB)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        liquorLayout.setVerticalGroup(
            liquorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liquorLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(liquorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vodkaB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scotchB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ginB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160))
        );

        view.add(liquor, "card2");

        beverage.setBackground(new java.awt.Color(255, 102, 51));

        cokeB.setText("Coke");
        cokeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeBActionPerformed(evt);
            }
        });

        gingerB.setText("Ginger");
        gingerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gingerBActionPerformed(evt);
            }
        });

        spriteB.setText("Sprite");
        spriteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout beverageLayout = new javax.swing.GroupLayout(beverage);
        beverage.setLayout(beverageLayout);
        beverageLayout.setHorizontalGroup(
            beverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverageLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cokeB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gingerB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spriteB)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        beverageLayout.setVerticalGroup(
            beverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beverageLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(beverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cokeB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gingerB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spriteB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        view.add(beverage, "card2");

        food.setBackground(new java.awt.Color(0, 255, 0));

        burgerB.setText("Burger");
        burgerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerBActionPerformed(evt);
            }
        });

        pizzaB.setText("Pizza");
        pizzaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaBActionPerformed(evt);
            }
        });

        croutonsB.setText("Croutons");
        croutonsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croutonsBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout foodLayout = new javax.swing.GroupLayout(food);
        food.setLayout(foodLayout);
        foodLayout.setHorizontalGroup(
            foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(burgerB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pizzaB)
                .addGap(18, 18, 18)
                .addComponent(croutonsB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        foodLayout.setVerticalGroup(
            foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(foodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burgerB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pizzaB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(croutonsB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        view.add(food, "card2");

        categories.setBorder(javax.swing.BorderFactory.createTitledBorder("Categories"));

        beveragesB.setText("Beverages");
        beveragesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beveragesBActionPerformed(evt);
            }
        });

        liquorB.setText("Liquor");
        liquorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquorBActionPerformed(evt);
            }
        });

        foodB.setText("Food");
        foodB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout categoriesLayout = new javax.swing.GroupLayout(categories);
        categories.setLayout(categoriesLayout);
        categoriesLayout.setHorizontalGroup(
            categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liquorB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beveragesB, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        categoriesLayout.setVerticalGroup(
            categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesLayout.createSequentialGroup()
                .addComponent(liquorB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beveragesB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(foodB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        deleteB.setText("Delete");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity");

        totallabel.setText("TOTAL: ");

        qtylabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtylabelActionPerformed(evt);
            }
        });

        sendB.setText("Send");
        sendB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(qtylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sendB)
                                .addGap(18, 18, 18)
                                .addComponent(totallabel))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteB)
                                .addComponent(sendB))
                            .addComponent(totallabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(qtylabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        
        sum = sum - Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        totallabel.setText(Double.toString(sum) );
        model.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_deleteBActionPerformed

    private void foodBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodBActionPerformed
        // TODO add your handling code here:

        view.removeAll();
        view.repaint();
        view.revalidate();

        view.add(food);
        view.repaint();
        view.revalidate();
    }//GEN-LAST:event_foodBActionPerformed

    private void liquorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquorBActionPerformed
        // TODO add your handling code here:
        view.removeAll();
        view.repaint();
        view.revalidate();

        view.add(liquor);
        view.repaint();
        view.revalidate();
    }//GEN-LAST:event_liquorBActionPerformed

    private void beveragesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beveragesBActionPerformed
        // TODO add your handling code here:

        view.removeAll();
        view.repaint();
        view.revalidate();

        view.add(beverage);
        view.repaint();
        view.revalidate();
    }//GEN-LAST:event_beveragesBActionPerformed

    private void croutonsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croutonsBActionPerformed
        price =  9.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,croutonsB.getText(),price, (qty*price)
            });
         qtylabel.setText(" ");
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
        }
    }//GEN-LAST:event_croutonsBActionPerformed

    private void pizzaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaBActionPerformed
        price =  8.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,pizzaB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
        }
    }//GEN-LAST:event_pizzaBActionPerformed

    private void burgerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerBActionPerformed
        
        price =  7.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,burgerB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_burgerBActionPerformed

    private void spriteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteBActionPerformed
        price =  1.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,spriteB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_spriteBActionPerformed

    private void gingerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gingerBActionPerformed

        price =  1.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,gingerB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_gingerBActionPerformed

    private void cokeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeBActionPerformed
        price =  1.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,cokeB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_cokeBActionPerformed

    private void ginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ginBActionPerformed
        price =  11.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,ginB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_ginBActionPerformed

    private void scotchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scotchBActionPerformed
        price =  14.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,scotchB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_scotchBActionPerformed

    private void qtylabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtylabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtylabelActionPerformed

    private void sendBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendBActionPerformed

    private void vodkaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vodkaBActionPerformed
        price =  12.50;
        if (qtylabel.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please select quantity");
        }
        else{
        qty = Integer.parseInt(qtylabel.getText());
        
        model = (DefaultTableModel)jTable1.getModel(); 
         
         
         model.addRow(new Object[]{
         
             qty,vodkaB.getText(),price, (qty*price)
            });
         qtylabel.setText("");
         sum = sum + (qty*price);
         totallabel.setText(Double.toString(sum) );
         
         
        }
    }//GEN-LAST:event_vodkaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sales1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beverage;
    private javax.swing.JButton beveragesB;
    private javax.swing.JButton burgerB;
    private javax.swing.JPanel categories;
    private javax.swing.JButton cokeB;
    private javax.swing.JButton croutonsB;
    private javax.swing.JButton deleteB;
    private javax.swing.JPanel food;
    private javax.swing.JButton foodB;
    private javax.swing.JButton ginB;
    private javax.swing.JButton gingerB;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel liquor;
    private javax.swing.JButton liquorB;
    private javax.swing.JButton pizzaB;
    private javax.swing.JTextField qtylabel;
    private javax.swing.JButton scotchB;
    private javax.swing.JButton sendB;
    private javax.swing.JButton spriteB;
    private javax.swing.JLabel totallabel;
    private javax.swing.JPanel view;
    private javax.swing.JButton vodkaB;
    // End of variables declaration//GEN-END:variables
}
